{% set name = "zipp" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 71c644c5369f4a6e07636f0aa966270449561fcea2e3d6747b8d23efaa9d7832
  patches:
    # See https://github.com/jaraco/zipp/pull/30
    - use-scm-version.patch

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=56
    - wheel
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.6

test:
  source_files:
    - test_zipp.py
  requires:
    - pip
    # this is a downstream that has a version requirement on zipp
    - importlib_metadata
    - jaraco.itertools
    - func_timeout
  imports:
    - zipp
  commands:
    - python -m unittest test_zipp.py
    - pip check

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  doc_url: https://zipp.readthedocs.io/en/latest
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - nehaljwani
